[package]
name = "music_player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "^0.16.2"
gtk = "^0.16.1"
crossbeam = "^0.3.0"
pulse-simple = "^1.0.0"
simplemad = "^0.8.1"
